import { NextResponse } from "next/server";
import OpenAI from "openai";
import { buildAIPrompt } from "@/ai-builder/prompt";
import { rateLimitCheck } from "@/server/rate-limit";

// ------------------------------
// 🔐 Load OpenAI Client
// ------------------------------
const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

// ------------------------------
// POST /api/ai-builder
// ------------------------------
export async function POST(req: Request) {
  try {
    const { answers } = await req.json();

    if (!answers) {
      return NextResponse.json(
        { error: "Missing answers object." },
        { status: 400 }
      );
    }

    // ------------------------------
    // 🔐 Rate Limiting
    // ------------------------------
    const rateExceeded = await rateLimitCheck("ai-builder");
    if (rateExceeded) {
      return NextResponse.json(
        { error: "Rate limit exceeded. Try again later." },
        { status: 429 }
      );
    }

    // ------------------------------
    // 🧠 Build the AI system prompt
    // ------------------------------
    const systemPrompt = buildAIPrompt(answers);

    // ------------------------------
    // 🤖 Call GPT-5.1-PRO
    // ------------------------------
    const response = await client.chat.completions.create({
      model: "gpt-5.1-pro", // 🔥 ENTERPRISE-GRADE ACCURACY
      messages: [
        {
          role: "system",
          content: systemPrompt,
        },
        {
          role: "user",
          content: "Begin generating the full infrastructure plan.",
        },
      ],
      temperature: 0.15,
      max_tokens: 8000,
      response_format: { type: "json_object" },
    });

    // ------------------------------
    // Parse & Validate AI Output
    // ------------------------------
    let output: any = null;

    try {
      output = JSON.parse(response.choices[0].message.content || "{}");
    } catch (err) {
      return NextResponse.json(
        {
          error:
            "Invalid JSON generated by the AI. Try adjusting your inputs or upgrading your plan.",
        },
        { status: 500 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        output,
      },
      { status: 200 }
    );
  } catch (err: any) {
    return NextResponse.json(
      {
        error: err.message || "Unexpected error occurred.",
      },
      { status: 500 }
    );
  }
}
