"use client";

import { useState } from "react";

interface ResultProps {
  result: any;
}

export default function AIBuildResult({ result }: ResultProps) {
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  const toggle = (key: string) => {
    setExpanded((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const copy = async (text: string) => {
    await navigator.clipboard.writeText(text);
  };

  const sections = [
    "summary",
    "architecture",
    "cloud_init",
    "docker_compose",
    "pipelines",
    "maintenance_plan",
    "sso_recommendations",
    "security_model",
    "budget_projection",
    "upgrade_paths",
    "next_steps",
  ];

  const renderSection = (key: string) => {
    if (!result[key]) return null;

    const isOpen = expanded[key];

    return (
      <div key={key} className="border border-neutral-800 rounded-lg mb-6">
        <button
          onClick={() => toggle(key)}
          className="w-full flex justify-between items-center px-4 py-3 bg-neutral-900 hover:bg-neutral-800 font-semibold text-left"
        >
          <span className="capitalize">{key.replace(/_/g, " ")}</span>
          <span>{isOpen ? "▲" : "▼"}</span>
        </button>

        {isOpen && (
          <div className="px-4 py-4 bg-black/40 text-sm overflow-x-auto">
            {/* Copy button */}
            <div className="flex justify-end mb-2">
              <button
                onClick={() =>
                  copy(
                    typeof result[key] === "string"
                      ? result[key]
                      : JSON.stringify(result[key], null, 2)
                  )
                }
                className="px-3 py-1 text-xs bg-blue-600 hover:bg-blue-700 rounded"
              >
                Copy
              </button>
            </div>

            <pre className="whitespace-pre-wrap">
{typeof result[key] === "string"
  ? result[key]
  : JSON.stringify(result[key], null, 2)}
            </pre>
          </div>
        )}
      </div>
    );
  };

  return (
    <section className="mt-16">
      <h2 className="text-3xl font-bold mb-6">Your AI-Generated Architecture</h2>

      {sections.map((key) => renderSection(key))}

      <div className="mt-10 text-gray-400 text-xs">
        Generated by DevVelocity AI Builder.
      </div>
    </section>
  );
}
